package com.bob.db.enums;

public enum PreOnboardingDocumentType {
    ADDRESS_PROOF,
    PAN_CARD,
    PASSPORT,
    VOTER_ID,
    DRIVING_LICENSE,
    DISABILITY_CERTIFICATE,
    QUALIFICATION_CERTIFICATE,
    EXPERIENCE_CERTIFICATE,
    GRATUITY_NOMINEE_PROOF,
    RESIDENTIAL_PROOF,
    OTHER
}