app.base.url=https://stage.bobjava.sentrifugo.com
ui.base.url=https://bobstage.candidate.sentrifugo.com

# ===================================================================
# Vault settings
# ===================================================================
# Force strict import to see the real connection error
spring.config.import=optional:vault://

spring.cloud.vault.uri=https://10.0.0.5:8201
spring.cloud.vault.ssl.trust-store=file:/opt/ssl/dev/vault-truststore.p12
spring.cloud.vault.ssl.trust-store-password=${VAULT_TRUSTSTORE_PASSWORD}
spring.cloud.vault.ssl.trust-store-type=PKCS12
spring.cloud.vault.ssl.external-key-store-validation=false

spring.cloud.vault.authentication=APPROLE
spring.cloud.vault.app-role.role-id=${VAULT_ROLE_ID}
spring.cloud.vault.app-role.secret-id=${VAULT_SECRET_ID}
spring.cloud.vault.app-role.app-role-path=approle

# Matches your UI 'Secrets / bob-dev / bob-dev'
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=bob-secrets
spring.cloud.vault.kv.default-context=stage
spring.cloud.vault.kv.version=2

# Error Handling
#spring.cloud.vault.fail-fast=true
logging.level.org.springframework.cloud.vault=DEBUG

# ===================================================================
# Core / Server / Spring Boot
# ===================================================================
server.servlet.context-path=/${spring.application.name}
spring.jackson.time-zone=Asia/Kolkata
server.ssl.enabled=true
server.ssl.key-store=/opt/ssl/dev/keystore.p12
server.ssl.key-store-password=${v-ssl-pass}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
server.forward-headers-strategy=framework
spring.thymeleaf.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===================================================================
# Azure related settings
# ===================================================================
useAzureBlob=true
azure.storage.connection-string=${v-blob-storage-connection-string}
azure.storage.container-name=${v-blob-storage-container-name}

# ===================================================================
# Azure AD related settings
# ===================================================================
spring.cloud.azure.active-directory.tenant-id=${v-azure-tenant-id}
spring.cloud.azure.active-directory.client-id=${v-azure-client-id}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${v-azure-issuer-uri}

# ===================================================================
# Database (JPA / Hikari)
# ===================================================================
spring.datasource.url=${v-db-url}
spring.datasource.username=${v-db-user}
spring.datasource.password=${v-db-pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=5
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# ===================================================================
# Logging
# ===================================================================
logging.level.org.springframework.web=DEBUG
logging.level.com.fasterxml.jackson=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG
log.file.path=/opt/tomcat/logs/stage/${spring.application.name}.log
logging.file.name=${log.file.path}
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=3MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.clean-history-on-start=true

# ===================================================================
# Email
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${v-email-user}
spring.mail.password=${v-email-pass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===================================================================
# Security / Auth0 / JWT
# ===================================================================
auth0.domain=https://dev-0rb6h2oznbwkonhz.us.auth0.com
auth0.connection=Username-Password-Authentication
auth0.jwt.jwk-set-uri=https://dev-0rb6h2oznbwkonhz.us.auth0.com/.well-known/jwks.json

# Auth0 Clients
auth0.recruiter.client-id=${v-auth0-client}
auth0.recruiter.client-secret=${v-auth0-secret}

#auth0.candidate.client-id=${v-auth0-cand-client}
#auth0.candidate.client-secret=${v-auth0-cand-secret}

auth0.m2m.client-id=${v-auth0-m2m-client}
auth0.m2m.client-secret=${v-auth0-m2m-secret}

# JWT
app.jwt.secret=${v-jwt-secret}
jwt.expiration=3600000
app.otp.expiration-minutes=5
app.verification.base-url=${app.base.url}/auth-portal/api/v1/candidate-auth/verify-token
ui.candidate.url = ${ui.base.url}/login

# ===================================================================
# Cloudflare
# ===================================================================
cloudflare.turnstile.secret-key=${v-cloudflare-secret}
cloudflare.turnstile.site-key=${v-cloudflare-site}
cloudflare.turnstile.verify-url=https://challenges.cloudflare.com/turnstile/v0/siteverify

# ===================================================================
# AI Services (OpenAI / Gemini)
# ===================================================================
openai.api.key=${v-openapi-key}
openai.api.url=https://api.openai.com/v1/chat/completions

openai.embedding.url=https://api.openai.com/v1/embeddings
openai.embedding.model=text-embedding-3-small

gemini.api.key=
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# ===================================================================
# Microsoft / Azure / Graph
# ===================================================================
# Azure connection settings
ms.graph.tenant-id=${v-ms-tenant-id}
ms.graph.client-id=${v-ms-client-id}
ms.graph.client-secret=${v-ms-client-secret}
ms.graph.scope=https://graph.microsoft.com/.default
ms.graph.email=mahesh.allvar@sagarsoft.in
ms.graph.url.access-token=https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/token
ms.graph.url.create-event=https://graph.microsoft.com/v1.0/users/{user-email}/events

# Microsoft Calendar
ms.tenant-id=${v-ms-tenant-id}
ms.client-id=${v-ms-client-id}
ms.client-secret=${v-ms-client-secret}

# ===================================================================
# DigiLocker
# ===================================================================
digilocker.client.id=${v-digilocker-client}
digilocker.client.secret=${v-digilocker-secret}
digilocker.base.url=https://digilocker.meripehchaan.gov.in/public
digilocker.auth.path=/oauth2/1/authorize
digilocker.token.path=/oauth2/1/token
digilocker.issued.path=/oauth2/2/files/issued
digilocker.eaadhaar.path=/oauth2/3/xml/eaadhaar
digilocker.file.path=/oauth2/1/file
digilocker.default.code=${v-digilocker-default-code}
digilocker.default.codechallenge=${v-digilocker-default-code-challenge}
digilocker.default.state=${v-digilocker-default-state}
digilocker.default.codeverifier=${v-digilocker-default-codeverifier}
digilocker.default.redirecturi=http://localhost:8003/doc.php
digilocker.default.granttype=authorization_code
digilocker.upload.success.url=${ui.base.url}/digilocker-upload-callback
digilocker.uploaded.path=/oauth2/1/files/uploaded

# ===================================================================
# File Storage / Uploads / Documents / Remote Host
# ===================================================================
# Remote Host
remote.host.url=na
remote.host.user=na
remote.host.password=na

filedownload.http.url=${app.base.url}/master-portal/api/v1/master/azureblob/download-file

# Resume Upload
resume.upload.path=/documents/Recruiter/Resumes
resume.http.url=

# Candidate Documents
candidate.attachment.upload.path=/documents/Candidate/candidate_attachments
candidate.attachment.http.url=
candidate.document.upload.path=/documents/Candidate/candidate_doc
candidate.offer.upload.path=/documents/Candidate/candidate_offers

# General Uploads
upload.doc-storage-path=/documents/Candidate
upload.public-base-url=

# Offer Templates
offertemplates.storage-path=/documents/Recruiter/OfferTemplates
offertemplates.public-base-url=

# Offer Letters
offerletters.storage-path=/documents/Recruiter/OfferLetters
offerletters.public-base-url=

# Generic Documents
generic.documents.upload.dir=/documents/Recruiter/GenericDocuments
generic.documents.upload.url=

# Indents
indent.upload.dir=/documents/Recruiter/Indents
indent.http.url=

# ===================================================================
# API Base Paths
# ===================================================================
candidate.api.base.path=/api/v1/candidate
master.api.base.path=/api/v1/master
recruiter.api.base.path=/api/v1/recruiter


# ===================================================================
# CCAvenue Properties
# ===================================================================
ccavenue.workingKey=${v-cc-workingkey}
ccavenue.accessCode=${v-cc-accesscode}
ccavenue.merchantId=${v-cc-merchantid}
ccavenue.redirect.url=${app.base.url}/candidate-portal${candidate.api.base.path}/cc-avenue-order/handleCallback
ccavenue.redirect.success.url=${ui.base.url}/candidate-portal/payment-success
ccavenue.redirect.failure.url=${ui.base.url}/candidate-portal/payment-failed
ccavenue.status.inquiry.url=${app.base.url}/${candidate.api.base.path}/cc-avenue-order/status
ccavenue.url=${v-cc-url}

logging.level.org.springframework.retry=DEBUG

# ===================================================================
# SMS Service Configuration
# ===================================================================
# SMS Gateway URI - Base URL for the SMS API
sms.gateway.uri=${v-sms-gateway-uri}

# SMS API configuration
sms.api.key=${v-sms-api-key}
sms.channel=${v-sms-channel}
sms.templateId.jobapply=${v-sms-templateId-jobapply}
sms.templateId.registration=${v-sms-templateId-registration}
sms.templateId.otp=${v-sms-templateId-otp}
# OAuth configuration for SMS service
sms.oauth.client.id=${v-sms-oauth-client-id}
sms.oauth.client.secret=${v-sms-oauth-client-secret}

# SMS certificate files
sms.certificate.bank.public.key=${v-sms-certificate-bank-public-key}
sms.certificate.private.key=${v-sms-certificate-private-key}